jobs:
  pmd-code-scan:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      id: pmd
      name: Run PMD
      uses: pmd/pmd-github-action@40392a149b9cfa24bf4c03989cc762e6814668bd
      with:
        analyzeModifiedFilesOnly: false
        rulesets: ruleset.xml
        sourcePath: src/main
    - continue-on-error: true
      name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: pmd-report.sarif
name: pmd
on:
  repository_dispatch:
    types: trigger-ga___pmd.yml
permissions:
  contents: read
